vich_uploader:
    db_driver: orm

    mappings:
       application_cvs:
           uri_prefix: '%app.path.application_cvs%'
           upload_destination: '%kernel.project_dir%/public%app.path.application_cvs%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
