version: "3"
services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
        #- "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pci
  
  adminer:
    image: adminer
    depends_on:
      - "db"
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: pci

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - "./public/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    depends_on:
      - "db" 
    user: 1000:1000
