version: "3.7"
services:
  mysql:
    image: mysql:5.6
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - "./public/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/defaut.conf:ro"
    ports:
      - "80:80"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000


