version: "3"
services:
  mysql:
    image: mysql:5.5
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pci
    networks:
      - mysql-compose-network
  
  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - mysql-compose-network

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - "./public/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000

networks:
  mysql-compose-network:
    driver: bridge


